// Validates a commit message against the Conventional Commits specification
// using the rules from @commitlint/config-conventional.
//
// Usage: commit-msg <msg-file>
package main

import (
	"fmt"
	"os"
	"strings"
	"unicode"
)

var allowedTypes = map[string]bool{
	"build":    true,
	"chore":    true,
	"ci":       true,
	"docs":     true,
	"feat":     true,
	"fix":      true,
	"perf":     true,
	"refactor": true,
	"revert":   true,
	"style":    true,
	"test":     true,
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: commit-msg <msg-file>")
		os.Exit(1)
	}

	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "commit-msg: %v\n", err)
		os.Exit(1)
	}

	lines := strings.Split(strings.ReplaceAll(string(raw), "\r\n", "\n"), "\n")

	// Strip comment lines.
	filtered := lines[:0]
	for _, l := range lines {
		if !strings.HasPrefix(l, "#") {
			filtered = append(filtered, l)
		}
	}
	lines = filtered

	if len(lines) == 0 {
		fatal("commit message is empty")
	}

	header := lines[0]

	// Skip merge/revert messages generated by Git itself.
	if strings.HasPrefix(header, "Merge ") || strings.HasPrefix(header, "Revert \"") {
		os.Exit(0)
	}

	var errs []string
	var warns []string

	adderr := func(msg string) { errs = append(errs, msg) }
	addwarn := func(msg string) { warns = append(warns, msg) }

	// header-trim
	trimmed := strings.TrimSpace(header)
	if header != trimmed {
		adderr("header must not have leading or trailing whitespace")
	}
	header = trimmed

	// header-max-length: 100
	if len(header) > 100 {
		adderr(fmt.Sprintf("header exceeds 100 characters (%d)", len(header)))
	}

	// Parse: type(scope)?!?: subject
	typePart, subject, ok := parseHeader(header)
	if !ok {
		adderr("header must match format: type(scope)?: description")
		adderr("  allowed types: " + allowedTypeList())
		printResults(errs, warns)
		os.Exit(1)
	}

	// type-enum
	if !allowedTypes[typePart] {
		adderr(fmt.Sprintf("type %q is not allowed; must be one of: %s", typePart, allowedTypeList()))
	}

	// subject-full-stop
	if strings.HasSuffix(subject, ".") {
		adderr("subject must not end with a period")
	}

	// subject-case: sentence-case, start-case, pascal-case, upper-case are never allowed.
	// All four begin with an uppercase letter.
	if len(subject) > 0 && unicode.IsUpper(rune(subject[0])) {
		adderr("subject must not start with an uppercase letter (sentence-case, start-case, pascal-case, and upper-case are not allowed)")
	}

	// body-leading-blank (warning) and line-length checks.
	if len(lines) > 1 {
		if lines[1] != "" {
			addwarn("body should be separated from header by a blank line")
		}
		for i, line := range lines[1:] {
			if len(line) > 100 {
				adderr(fmt.Sprintf("line %d exceeds 100 characters (%d)", i+2, len(line)))
			}
		}
	}

	printResults(errs, warns)
	if len(errs) > 0 {
		os.Exit(1)
	}
}

// parseHeader splits "type(scope)?!?: subject" into (type, subject, ok).
func parseHeader(header string) (string, string, bool) {
	// Find the ": " separator.
	prefix, subject, ok := strings.Cut(header, ": ")
	if !ok {
		return "", "", false
	}

	if subject == "" {
		return "", "", false
	}

	// Strip optional "!" (breaking change marker).
	prefix = strings.TrimSuffix(prefix, "!")

	// Strip optional "(scope)".
	if i := strings.Index(prefix, "("); i >= 0 {
		if !strings.HasSuffix(prefix, ")") {
			return "", "", false
		}
		prefix = prefix[:i]
	}

	// type must be non-empty lowercase letters only.
	if prefix == "" {
		return "", "", false
	}
	for _, r := range prefix {
		if !unicode.IsLower(r) {
			return "", "", false
		}
	}

	return prefix, subject, true
}

func allowedTypeList() string {
	types := []string{"build", "chore", "ci", "docs", "feat", "fix", "perf", "refactor", "revert", "style", "test"}
	return strings.Join(types, " ")
}

func printResults(errs, warns []string) {
	for _, w := range warns {
		fmt.Fprintf(os.Stderr, "commit-msg: warning: %s\n", w)
	}
	for _, e := range errs {
		fmt.Fprintf(os.Stderr, "commit-msg: error: %s\n", e)
	}
}

func fatal(msg string) {
	fmt.Fprintf(os.Stderr, "commit-msg: error: %s\n", msg)
	os.Exit(1)
}
